services:
  - type: web
    name: vizstra-backend
    env: node
    rootDir: backend/baceknd
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  - type: static
    name: vizstra-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_BACKEND_URL
        fromService:
          type: web
          name: vizstra-backend
          property: host
